### ISSUE TITLE
bind interface '-i' incomplete

### ISSUE THREAD

**Issue by Andy2244** [Andy2244/wsdd2#3]
> Connecting from an unprotected WAN still seems to succeed. I suppose the socket code will need to be amended to only bind to the interface's IP address, and not to 0.0.0.0.

```
netstat -an | egrep 3702
tcp        0      0 0.0.0.0:3702            0.0.0.0:*               LISTEN
tcp        0      0 :::3702                 :::*                    LISTEN
udp        0      0 0.0.0.0:3702            0.0.0.0:*
udp        0      0 :::3702                 :::*

```

**Comment by Andy2244** [comment]
@namjaejeon Just got this working with cifsd, so maybe you can take a quick look on the interface code and how to prevent the extra binds?

**Comment by themiron** [comment]
I hope #4 could help

**Comment by Andy2244** [comment]
thanks, need to verify if still reachable via wan

**Comment by themiron** [comment]
@Andy2244 sockets still listen on 0.0.0.0/:: due the design, but since sockets are bind now they can't send packets via "wrong" interfaces. further improvement would be move to recvmsg() with IP_PKTINFO/IPV6_PKTINFO and check received ifindex

**Comment by Andy2244** [comment]
@themiron yes i understand, cifsd is doing it the same way. Its fine for now i think, thanks again.
